Repository firebase/firebase-admin-go, pull requests merged in 2021-12, with the labels that each got.

#468 feat(auth): enables OIDC Auth code flow
  auth/provider_config.go
  auth/provider_config_test.go
Labels: release-note

#472 Fix integration tests for OIDC code flow
  .gitignore
  integration/auth/provider_config_test.go
Labels: release:stage

#473 [chore] Release 4.7.0
  firebase.go
Labels: release:tweet, release:publish
