Repository firebase/firebase-admin-go, pull requests merged in 2023-09, with the labels that each got.

#530 fix(auth): Allow to update MFA
  auth/user_mgt.go
  auth/user_mgt_test.go
Labels: release-note

#581 [chore] Release 4.12.1
  firebase.go
Labels: release:stage, release:tweet, release:publish

#583 [chore] Release 4.12.1
  firebase.go
Labels: release:publish

#584 [chore] Release Debugging release.yml
  .github/workflows/release.yml
Labels: release:stage, release:publish

#585 [chore] Release 4.12.1 take 3
  .github/workflows/release.yml
Labels: release:tweet, release:publish
