Repository firebase/firebase-admin-go, pull requests merged in 2024-10, with the labels that each got.

#638 feat(fcm): enable direct_boot_ok as bool in Android config
  messaging/messaging.go
  messaging/messaging_test.go
Labels: release-note

#646 chore: Skip integration tests for deprecated FCM APIs
  integration/messaging/messaging_test.go
Labels: release:stage

#645 fix(fcm): Change `DirectBootOK` per Go initialisms
  messaging/messaging.go
  messaging/messaging_test.go
Labels: release-note, release:stage

#647 chore: Upgrade Go version support
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  README.md
  go.mod
Labels: release-note, release:stage

#648 chore: Add X-Goog-Api-Client header to Auth and FCM requests
  auth/auth.go
  auth/auth_test.go
  auth/user_mgt_test.go
  messaging/messaging.go
  messaging/messaging_test.go
Labels: release:stage
