Repository firebase/firebase-admin-go, pull requests merged in 2025-07, with the labels that each got.

#697 feat(rc): Implementation of Server-side Remote Config
  firebase.go
  internal/internal.go
  remoteconfig/condition_evaluator.go
  remoteconfig/condition_evaluator_test.go
  remoteconfig/remoteconfig.go
  remoteconfig/remoteconfig_test.go
  remoteconfig/server_config.go
  remoteconfig/server_config_test.go
  remoteconfig/server_template.go
  remoteconfig/server_template_test.go
  remoteconfig/server_template_types.go
Labels: release-note, release:stage

#707 [chore] Release 4.17.0
  firebase.go
Labels: release:stage, release:publish

#709 Bump `crypto` to `0.40.0` and `net` to `0.42.0`
  go.mod
  go.sum
Labels: release:stage
